### ISSUE TITLE
open in modal popup bootstrap 3

### ISSUE THREAD

**Issue by ezera23** [SimplySayHi/surveyJS#1]
Hello,

I have a problem when i try to call the survey from a modal popup. The bottom part of the slider didn't show then when i  got to the next step it works.

if i try to open the popup before other elements of the page are fully loaded then i have the full survey (with the bottom part)

Do you have any ideas for get it working?

Regards

**Comment by SimplySayHi** [comment]
> Hello,
> 
> I have a problem when i try to call the survey from a modal popup. The bottom part of the slider didn't show then when i got to the next step it works.
> 
> if i try to open the popup before other elements of the page are fully loaded then i have the full survey (with the bottom part)
> 
> Do you have any ideas for get it working?
> 
> Regards

Hi @ezera23,
can you please create a jsfiddle ( or else ) to reproduce the issue?
In addition, a detailed explanation of the problem with all the steps would be great :)

Thanks

**Comment by ezera23** [comment]
Hi Valerio!

You can reproduce the issue [here](https://amcoachsportif.com)

Here the step for trigger the issue:

Reach the website
Wait the full loading
Click on "Je démarre" (the yellow button at the right of the slider)
The button Send (the bottom part of surveyjs) of the slider doesn't appear
Then click on the arrow right for go to the next step from the surveyjs and it's appear
you can come back to the previous step, now the bottom part of the survey is still here and the issue is "fixed".

Now let's try this:

Reach the website
**Don't wait** the page to be fully loaded
Click on "Je démarre" (the yellow button at the right of the slider) before the full page laoding
Here the issue didn't show up and the survey appear in full and perfectly without any issue.

regards

**Comment by SimplySayHi** [comment]
Hi @ezera23 

I think the problem is that the modal is hidden when you initialize the slider ( it's a common issue with sliders in general ).
You can initialize the survey at page load, if you prefer, but I suggest you to try to initialize the slider only when you are showing the modal because otherwise it cannot calculate the right height for the slider. You can try with Bootstrap 3 event "show.bs.modal" or "shown.bs.modal".

Let me know if this can solve your problem ;)

**Comment by ezera23** [comment]
Hi Valerio,

Thanks for your answer, I tried it show and shown and unfortunately it's not the solution. I also tried to invoke surveyjs from the show.bs.modal without success. I have also tried to edit the bootstrap css modal by replacing the display none by a display block and visibilty hidden for avoid sizing calculation problem at initialization but its not woring too.

What about your idea to initialize the survey at page load? do you mean to automatically show it at page load? If yes, unfortunately it's not possible as i have to trigger it when button is clicked.

**Comment by SimplySayHi** [comment]
Hi @ezera23 

from your page I can see that you are still calling the survey init method at page load.
You need to remove it from there and call it when you open the modal, like:
```
$('#multistep').on('show.bs.modal', function(){
    mySurvey.init()
            .then(function( data ){
                console.log('retrieveSurvey init then');
                onInitSuccess.call(mySurvey, data);
            })
            .catch(function( error ){
                console.log('retrieveSurvey init catch');
                onInitError.call(mySurvey, error);
            });
});
```

**Comment by ezera23** [comment]
Hi @SimplySayHi 

i tried it but im not sure. I sent you an email with direct access did you received it?

regards

**Comment by SimplySayHi** [comment]
Hi @ezera23 ,

sorry for the delay, I've been very busy.

I appreciate your trust for me but I think it's better to start slowly ( it's very dangerous to give your server credentials to someone you don't know :) ). If you want to start a collaboration, I'm always available.

For your issue with survey, I created a jsfiddle with the code you need to use.
AJAX call to get json data it's not actually working from jsfiddle bacause of it's restrictions but the code will work for your case.
This is the link to the fiddle:
https://jsfiddle.net/9qog18uv/

Let me know if this can solve your issue
